### ISSUE TITLE
No member named 'getFixedUpdateStep' in 'bs::Application'

### ISSUE THREAD

**Issue by crookedbard** [GameFoundry/bsfExamples#10]
Examples>Common>Source Files>BsFPSWalker.cpp Line 63
const float frameDelta = gApplication().getFixedUpdateStep();

Xcode throws: No member named 'getFixedUpdateStep' in 'bs::Application'

**Comment by BearishSun** [comment]
Thanks for the report. This should now be resolved on latest master.
