### ISSUE TITLE
macOS 10.14 OpenGL is deprecated. 

### ISSUE THREAD

**Issue by crookedbard** [GameFoundry/bsfExamples#11]
It would be great to have some examples of Vulkan renderer. 
[img of Xcode build](https://imgur.com/a/SFt2b4o)

**Comment by BearishSun** [comment]
Can you try adding `-Wno-deprecated-declarations` to `bsf/Source/CMake/Properties.cmake`, line 91. This one:

```
	if(APPLE)
		set(BS_COMPILER_FLAGS_COMMON "${BS_COMPILER_FLAGS_COMMON} -fobjc-arc -std=c++1z")
	endif()
```

See if that gets rid of the warnings? If it works let me know, or just make a PR with the change.

We won't be dropping support for OpenGL on macOS any time soon, so it's best to ignore the warnings. Vulkan is not natively supported either, but when I get a moment I might add support for it through the MoltenVK layer - there's a short discussion about it [here](https://github.com/GameFoundry/bsf/issues/19).

**Comment by crookedbard** [comment]
Yes I was able to silence these warnings, also Xcode suggest to define GL_SILENCE_DEPRECATION to silence GL warnings. But knowing Apple if they deprecate something in one version then in other they may remove this support.
