### ISSUE TITLE
GUI.exe on button click crashed.

### ISSUE THREAD

**Issue by crookedbard** [GameFoundry/bsfExamples#12]
[link to log.html from bs crash reports folder](https://nofile.io/f/OBve51VMsHX/log.html)

Type | Description
-- | --
Debug | User selected element: "Black"in auto __cdecl bs::setUpGUI::::operator ()(unsigned int,bool) const [c:\users\dkr\documents\source\repos\bsfexamples\source\gui\main.cpp:140]
Error | A fatal error occurred and the program has to terminate!- Error: InternalErrorException- Description: Trying to access an object that has been destroyed.- In function: void __cdecl bs::GameObjectHandleBase::throwIfDestroyed(void) const- In file: c:\users\dkr\documents\source\repos\bsf\source\foundation\bsfcore\scene\bsgameobjecthandle.cpp:51Stack trace: bs::CrashHandler::reportCrash() - 0x140717506311936 File[bswin32crashhandler.cpp:468 (0)] Module[bsf.dll]bs::GameObjectHandleBase::throwIfDestroyed() - 0x140717509321801 File[bsgameobjecthandle.cpp:51 (120)] Module[bsf.dll]bs::SceneManager::processStateChanges() - 0x140717509415992 File[bsscenemanager.cpp:430 (8)] Module[bsf.dll]bs::SceneManager::_fixedUpdate() - 0x140717509416551 File[bsscenemanager.cpp:506 (0)] Module[bsf.dll]bs::CoreApplication::runMainLoop() - 0x140717509268577 File[bscoreapplication.cpp:236 (33)] Module[bsf.dll]WinMain() - 0x140698551540055 File[main.cpp:321 (0)] Module[GUI.exe]__scrt_common_main_seh() - 0x140698551549374 File[exe_common.inl:283 (33)] Module[GUI.exe]0x140719231672292 Module[KERNEL32.DLL]0x140719271374945 Module[ntdll.dll]

**Comment by BearishSun** [comment]
Thanks for the report. This is likely related to https://github.com/GameFoundry/bsf/issues/173

**Comment by BearishSun** [comment]
This should be resolved with https://github.com/GameFoundry/bsf/commit/440391ccb2cefb7d862beaa37004582a2933189a
