### ISSUE TITLE
Audio example crashes while trying to load .ogg files

### ISSUE THREAD

**Issue by technicallyagd** [GameFoundry/bsfExamples#14]
Hi, I compiled the examples on `Ubuntu 18.04` using `Ninja`. All examples ran perfectly, except for the `Audio` example. The `Audio` example prints `symbol lookup error: libbsfOpenAudio.so: undefined symbol: oggpack_readinit` and then crashes. If I comment out the code that loads `.ogg` files, the example runs without problem. 
_EDIT: Forgot to mention the compiler was `GCC 8.1.0`_

**Comment by BearishSun** [comment]
Hi. Thanks for the report, I'm able to reproduce the issue. I'll let you know when it's resolved.

**Comment by BearishSun** [comment]
This issue should be resolved with https://github.com/GameFoundry/bsf/commit/d9f265ac09edd98ee495b7ce224e1ef91162eb92
