### ISSUE TITLE
Cmake build issue

### ISSUE THREAD

**Issue by 1n48yg** [GameFoundry/bsfExamples#22]
I'm relatively new to C++ compared to most of the other people here who have used BSF so pardon me if I miss something quite obvious or start being concerned over trivial matters. 

I'm trying to compile the bsfExamples, I've cloned the git repository and made a build folder inside of the generated repository. However everytime I run cmake the exact same error occurs: 
`-- ...Cannot find imported library: PhysX3_x86 PhysX3_x86_LIBRARY_RELEASE-NOTFOUND
-- ...Cannot find imported library: PhysX3Common_x86 PhysX3Common_x86_LIBRARY_RELEASE-NOTFOUND
-- ...Cannot find imported library: PhysX3Cooking_x86 PhysX3Cooking_x86_LIBRARY_RELEASE-NOTFOUND
-- ...Cannot find imported library: PhysX3CharacterKinematic_x86 PhysX3CharacterKinematic_x86_LIBRARY_RELEASE-NOTFOUND
CMake Error at bsf/Source/CMake/HelperMethods.cmake:172 (message):
  Cannot find PhysX installation.  Try modifying the PhysX_INSTALL_DIR path.
Call Stack (most recent call first):
  bsf/Source/CMake/Modules/FindPhysX.cmake:46 (end_find_package)
  bsf/Source/Plugins/bsfPhysX/CMakeLists.txt:5 (find_package)`

I've tried to delete all of the content inside of the bsfExamples folder then recompile, but this still yields the exact same error. Is my computer missing any software required to compile these files? I assume this can't be hardware incompatibility right?

**Comment by BearishSun** [comment]
Looks like you're trying to compile a 32-bit build of bsf, and while 32-bit builds are supported we don't provide pre-built dependencies for 32-bit (you have to build them yourselves). If you're on windows make sure to use the generator `Visual Studio 15 2017 Win64`, note the `Win64` at the end. If you're using VS 2019 then provide the `-A x64` flag.

**Comment by 1n48yg** [comment]
First of all, thanks for the fast response! That was almost instantaneous!

I've tried to recompile the 64 bit build, my command is: `cmake "Visual Studio 15 2017 Win64" ../`

But I'm still getting the same error as before, looking at the error it still seems to compile the 32 bit physX even when I specify to compile the 64 bit version of bsf. I'll post the error here in case something's different and I missed it.
`-- Looking for PhysX installation...
-- ...Cannot find imported library: PhysX3_x86 PhysX3_x86_LIBRARY_RELEASE-NOTFOUND
-- ...Cannot find imported library: PhysX3Common_x86 PhysX3Common_x86_LIBRARY_RELEASE-NOTFOUND
-- ...Cannot find imported library: PhysX3Cooking_x86 PhysX3Cooking_x86_LIBRARY_RELEASE-NOTFOUND
-- ...Cannot find imported library: PhysX3CharacterKinematic_x86 PhysX3CharacterKinematic_x86_LIBRARY_RELEASE-NOTFOUND
CMake Error at bsf/Source/CMake/HelperMethods.cmake:172 (message):
  Cannot find PhysX installation.  Try modifying the PhysX_INSTALL_DIR path.
Call Stack (most recent call first):
  bsf/Source/CMake/Modules/FindPhysX.cmake:46 (end_find_package)
  bsf/Source/Plugins/bsfPhysX/CMakeLists.txt:5 (find_package)`

**Comment by BearishSun** [comment]
The command should be `cmake -G "Visual Studio 15 2017 Win64" ../`

**Comment by 1n48yg** [comment]
Thanks for the support, my issue is resolved!
