### ISSUE TITLE
Crash on macOS

### ISSUE THREAD

**Issue by TumblerSGQ** [GameFoundry/bsfExamples#24]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/12553991/66930690-8ed2fb00-f067-11e9-9759-e019d5a90b60.png">

**Comment by BearishSun** [comment]
We wont be supporting OpenGL on mac with the next release, so this is likely not getting fixed I'm afraid. Everything will be moved to Metal which should resolve any such issues.
