### ISSUE TITLE
Crash on maxOS

### ISSUE THREAD

**Issue by TumblerSGQ** [GameFoundry/bsfExamples#25]
![image](https://user-images.githubusercontent.com/12553991/67090536-f3639680-f1dc-11e9-9ee2-dfa5508af154.png)

**Comment by BearishSun** [comment]
Duplicate of #24. Will not fix as OpenGL is becoming deprecated on Mac. I suggest to switch to Vulkan renderer, if you can get the examples to work with latest bsf, otherwise you need to wait for the next stable release.
