### ISSUE TITLE
Closing Audio example causes crash

### ISSUE THREAD

**Issue by jayrulez** [GameFoundry/bsfExamples#3]
Closing the audio example using the close window icon causes a crash. This seems to be a race/timing issue as if I set a break point on the quitRequested method and step through then the application exits normally.

I've attached the log here:

[log.zip](https://github.com/GameFoundry/bsfExamples/files/1935032/log.zip)

**Comment by BearishSun** [comment]
Thanks for the report. I've managed to reproduce and fix the issue. The fix is live on the main bsf repository.
