### ISSUE TITLE
Visual studio 2017 15.7.1 "Unknown CMake command "copyBsfBinaries"."

### ISSUE THREAD

**Issue by jonesmz** [GameFoundry/bsfExamples#6]
Using Visual Studio's built in git and cmake support, I clone the bsfExamples repository, and set it to x64-Debug, and ask it to build everything. This is the error that I get.

1> Command line: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\jonesmz\CMakeBuilds\e09c658e-8640-ea34-b760-1ec62c1516f4\install\x64-Debug"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\jonesmz\Source\Repos\bsfExamples"
1> Working directory: C:\Users\jonesmz\CMakeBuilds\e09c658e-8640-ea34-b760-1ec62c1516f4\build\x64-Debug
1> -- Built dependencies are out of date, forcing recompile.
1> -- Looking for snappy installation...
1> -- ...snappy OK.
1> -- Looking for nvtt installation...
1> -- ...nvtt OK.
1> -- Looking for OpenAL installation...
1> -- ...OpenAL OK.
1> -- Looking for ogg installation...
1> -- ...ogg OK.
1> -- Looking for vorbis installation...
1> -- ...vorbis OK.
1> -- Looking for FLAC installation...
1> -- ...FLAC OK.
1> -- Looking for PhysX installation...
1> -- ...PhysX OK.
1> -- Looking for FBXSDK installation...
1> -- ...FBXSDK OK.
1> -- Looking for freetype installation...
1> -- ...freetype OK.
1> -- Looking for freeimg installation...
1> -- ...freeimg OK.
1> -- Looking for bison installation...
1> -- ...bison OK.
1> -- Looking for flex installation...
1> -- ...flex OK.
1> -- Building BSL lexer/parser...
1> -- Looking for XShaderCompiler installation...
1> -- ...XShaderCompiler OK.
1> CMake Error at Source/Common/CMakeLists.txt:18 (copyBsfBinaries):
1>   Unknown CMake command "copyBsfBinaries".
1> 
1> 
1> -- Configuring incomplete, errors occurred!
1> See also "C:/Users/jonesmz/CMakeBuilds/e09c658e-8640-ea34-b760-1ec62c1516f4/build/x64-Debug/CMakeFiles/CMakeOutput.log".
1> C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\jonesmz\CMakeBuilds\e09c658e-8640-ea34-b760-1ec62c1516f4\install\x64-Debug"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.14.26428/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\jonesmz\Source\Repos\bsfExamples" returned with exit code: 1
CMake Error at Source/Common/CMakeLists.txt:18 (copyBsfBinaries):
  Unknown CMake command "copyBsfBinaries".

**Comment by BearishSun** [comment]
Updating `bsf` the examples link to should solve the problem (its a function that was introduced a few days ago).

**Comment by BearishSun** [comment]
I'm assuming this was resolved.
